version: 0.0
os: linux
files:
  - source: ./
    destination: /Geostore-tests
  - source: src/web/app/target/geostore.war
    destination: /Geostore-tests/src/web/app/target/geostore.war
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

