version: 0.0
os: linux
files:
  - source: ./
    destination: /Geostore-tests
  - source: src/target/*
    destination: /Geostore-tests/src/target/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

