version: 0.0
os: linux
files:
  - source: /src/web/app/target/geostore.war
    destination: /opt/tomcat/webapps/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
