version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd src/
      - mvn clean install -Dovrdir=postgres -Ppostgres
      - ls -al target
      - cp target/*.jar web/app/target/
artifacts:
  files:
    - src/web/app/target/*
