version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd src/
      - mvn clean install -Dovrdir=postgres -Ppostgres
      - ls -al target
artifacts:
  files:
    - src/target/*.jar
   # - src/web/app/target/geostore.war
