name: Cut Release
on:
  workflow_dispatch:
    inputs:
      current-version:
        description: Current version (e.g. 2.1)
        required: true
      next-version: 
        description: Next version (e.g. 2.2). 
        required: true
jobs:
  cut-release:
    name: Create release branch and PRs into main (master)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout  
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create release branch and generate PR body
        id: create-branch
        env:
          CURR: ${{ github.event.inputs.current-version }}
          NEXT: ${{ github.event.inputs.next-version }}
        run: |
          # script will go here
          echo "Initializing git"
          git config user.name github-actions
          git config user.email github-actions@github.com
          BRANCH_NAME="${CURR}.x"
          echo "creating branch is $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"
          git checkout master
          mvn release:update-versions -DautoVersionSubmodules=true -DdevelopmentVersion=${NEXT}-SNAPSHOT # sets the internal verison
          mvn versions:set-property -Dproperty=geostore-version -DnewVersion=${NEXT}-SNAPSHOT # sets geostore-version property
          git add pom.xml
          git add "**/pom.xml"
          git commit -m "Update to ${NEXT}"
          git push origin master


          
